### ISSUE TITLE
Where Do PDFs Go? / Not Responding 

### ISSUE THREAD

**Issue by preflight** [bigmattyh/together-chrome-extension#1]
Thanks for creating this extension. I've installed it to Chrome but am seeing no result when selecting the PDF option. Can you tell me the default location for saving PDFs?

My versions are:
- OS X 10.8.5
- Together 3.1.7
- Chrome 45 (also tried in Chrome 43)

When I select Save to Together... PDF, the External Protocol Request window opens asking whether it's okay to open Together. Selecting `Launch Application` doesn't launch the app. I've tried with Together open and closed. I haven't checked "Remember my Choice."

**Comment by matthowell22** [comment]
Hi Michael,

So, the extension I've written is basically a nice-looking wrapper for the bookmarklets provided by the Together app. (You can see the bookmarklets in their javascript form by navigating to Preferences > Import > Bookmarklets…) The extension just passes the name, url, and type (i.e., PDF) to the bookmarklet, and the app handles the rest.

I'm on OSX 10.10.4, Together 3.4.2, and Chrome 43, so we're definitely in different environments, especially considering all the security changes that have been introduced in OSX and Chrome recently. 

I'd recommend that you troubleshoot using just the bookmarklet code (found in the preferences pane, listed above). If you can get a PDF to save using the bookmarklet, but not the extension, let me know, and I'll see if I can come up with a fix.

**Comment by preflight** [comment]
Thanks for replying -- I am able to get a PDF using the bookmarklet. It seems pretty likely that my old versions are the cause (I'm stuck on Mountain Lion at the moment unfortunately).

Do you happen to know if there is an option/flag I can set to save the PDF page size to Letter (8.5 x 11 inches)? Here's the bookmarklet code for reference:

```
javascript:location.href='x-together://AddItem?kind=WebPDF&name='+encodeURIComponent(document.title)+'&url='+encodeURIComponent(window.location);
```
